#define IDC_STATIC                      -1
#define IDD_JULIADLG                    100
#define IDD_STANDARD                    1000
#define IDD_STYLES                      1001
#define IDD_ANTI_JULIA                  1004
#define IDD_ANTI-JULIA                  1005
#define IDD_EXTREME                     1006
#define IDD_CAMELEON                    1007
#define 233                             1008
#define IDD_STATIC_1                    1010
#define IDD                             1011
#define IDD_STATIC_2                    1012
#define IDD_STATIC_C                    1013
#define ISS_STATIC_4                    1014
#define IDD_PARAMETERS                  101
#define IDD_STATIC_5                    1015
#define IDD_STATIC_6                    1018
#define IDD_AA                          1019
#define IDD_BB                          1020
#define IDD_P1                          1021
#define IDD_P2                          1022
#define IDD_COLOR_TRUE                  1023
#define IDD_COLOR_FALSE                 1024
#define IDD_HT_1                        1025
#define IDD_HT_2                        1026
#define IDD_HT_3                        1027
#define IDD_HT_4                        1028
#define IDD_HT_5                        1030
#define ISS_STATIC_3                    1032
#define IDD_TENTACLE                    1033
#define IDD_TIGER                       1034
#define IDD_SNAKE                       1035
#define IDD_MAN_STANDARD                1038
#define IDD_MAN_TIGER                   1039
#define IDD_M                           1040
#define IDD_MANDELBROT                  1041
#define IDD_DISTORTION                  1042
#define IDC_STATIC_DIST                 1044
#define IDDX                            1046
#define IDD_NODIST                      1047
#define IDD_S_DETAILS                   1048
#define IDC_DETAIL                      1049
#define IDD_DETAIL                      1050
#define IDD_EXTREME-ANTI                1051
#define IDD_COLOR                       1052
#define IDD_PATERN                      1053
#define IDD_PATTERN                     1054
#define RR                              1055
#define IDD_WIDTH                       1056
#define IDD_HEIGHT                      1057
